# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlainTextToGeometry
                                 A QGIS plugin
 Extract coordinates from plain text and create points, line or polygon
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-03-22
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Paweł Strzelewicz
        email                : @
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path
import re

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QWidget, QMessageBox, QTableWidgetItem
from qgis.core import (
    QgsFeature,
    QgsGeometry,
    QgsPointXY,
    QgsVectorLayer
)

# Initialize Qt resources from file resources.py
from .resources import *  # pylint: disable=unused-wildcard-import, wildcard-import
# Import the code for the dialog
from .plaintext_to_geometry_dialog import PlainTextToGeometryDialog

from .aviation_gis_toolkit.const import AT_LATITUDE, AT_LONGITUDE
from .aviation_gis_toolkit.coordinate_extraction import (
    SEQUENCE_LON_LAT,
    SEQUENCE_LAT_LON,
    CoordinatePairExtraction
)
from .aviation_gis_toolkit.coordinate import Coordinate
from .exceptions import FormValidationException, AddingFeaturesException
from .layer_utils import (
    create_output_layer,
    find_vector_layers,
    get_potential_output_layers,
    create_features,
    add_features_to_layer
)


class PlainTextToGeometry:
    """QGIS Plugin Implementation."""

    def __init__(self, iface) -> None:
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.coordinate_extractor: CoordinatePairExtraction | None = None
        self.output_layer = None
        self.coordinates_extracted = False
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            f'PlainTextToGeometry_{locale}.qm')

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr('&PlainTextToGeometry')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message) -> str:
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('PlainTextToGeometry', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None
    ) -> QAction:
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self) -> None:  # pylint: disable=invalid-name
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/plaintext_to_geometry/icon.png'
        self.add_action(
            icon_path,
            text=self.tr('PlainTextToGeometry'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self) -> None:
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr('&PlainTextToGeometry'),
                action)
            self.iface.removeToolBarIcon(action)

    def input_data_changes(self) -> None:
        """ Clear marking for extracted coordinates and reset coordinate list in case:
            - plain text is edited
            - geometry type changes """
        if self.coordinates_extracted:
            self.dlg.clear_extracted_coordinates()

    def set_coordinate_pair_format(self) -> None:
        """Set the coordinate pair format from GUI selections."""
        if not self.dlg.is_coordinate_format_set():
            self.coordinate_extractor = None
            self.dlg.clear_extracted_coordinates()
            self.dlg.labelCoordinatesExample.setText(
                'Define coordinate format to see example'
            )
            return

        self.set_coordinate_extractor()
        self.dlg.clear_extracted_coordinates()
        self.show_sample_coordinate_format()

    def set_coordinate_extractor(self) -> None:
        """Initiate CoordinatePairExtraction instance based on the coordinate pair format settings"""
        self.coordinate_extractor = CoordinatePairExtraction(
            coord_sequence=self.dlg.comboBoxCoordinatesSequence.currentData(),
            coord_format=self.dlg.comboBoxCoordinatesFormat.currentData(),
            coord_sep=self.dlg.comboBoxCoordinatesSeparator.currentData(),
        )

    def show_sample_coordinate_format(self) -> None:
        """Display example of coordinate pair based on the on the coordinate pair format settings"""
        example_coordinates = self.coordinate_extractor.get_coordinates_pair_example()
        self.dlg.labelCoordinatesExample.setText(example_coordinates)

    def get_matching_layers_from_map(self, layer_name: str) -> list[QgsVectorLayer] | None:
        """ Check layers in Layer (TOC) in current Qgs Project and return those layers that match
        plugin PlainTextToGeometry output layer.
        param layer_name: str
        return: list -> QgsVectorLayer
        """
        vector_layers = find_vector_layers(layer_name)
        if vector_layers:
            candidate_layers = get_potential_output_layers(layers=vector_layers,
                                                           geometry_type=self.dlg.get_output_geometry_type())
            return candidate_layers

    def get_coordinates_from_plain_text(self) -> list[tuple[str, str]]:
        plain_text = self.dlg.textEditPlainText.toHtml()
        coordinates = self.coordinate_extractor.extract_coordinates(plain_text)
        return coordinates

    def mark_coordinates(self, coordinates: list[tuple[str, str]]) -> None:
        """ Mark extracted coordinates in plain text - set the color to green.
        param coordinates: list, list of extracted coordinates
        """
        if coordinates:
            text = self.dlg.textEditPlainText.toHtml()
            for c1, c2 in coordinates:
                coord_pair = f'{c1}{self.coordinate_extractor.coord_sep}{c2}'
                text = re.sub(coord_pair, f'<span style="color:green;">{coord_pair}</span>', text)

            self.dlg.textEditPlainText.setHtml(text)

    def insert_coordinates_to_list(self, lon: str, lat: str) -> None:
        row_pos = self.dlg.tableWidgetCoordinates.rowCount()
        self.dlg.tableWidgetCoordinates.insertRow(row_pos)
        self.dlg.tableWidgetCoordinates.setItem(row_pos, 0, QTableWidgetItem(lon))
        self.dlg.tableWidgetCoordinates.setItem(row_pos, 1, QTableWidgetItem(lat))

    def fill_in_coordinate_list(self, coordinate_list) -> None:
        self.dlg.tableWidgetCoordinates.setRowCount(0)
        if self.coordinate_extractor.coord_sequence == SEQUENCE_LON_LAT:
            for lon, lat in coordinate_list:
                self.insert_coordinates_to_list(lon, lat)
        elif self.coordinate_extractor.coord_sequence == SEQUENCE_LAT_LON:
            for lat, lon in coordinate_list:
                self.insert_coordinates_to_list(lon, lat)

    def get_qgspoints(self) -> list[QgsPointXY]:
        """ Create list of QgsPoints based on extracted coordinates.
        return: points: list of QGsPoint
        """
        points = []
        points_count = self.dlg.tableWidgetCoordinates.rowCount()

        for i in range(0, points_count):
            lon = Coordinate(self.dlg.tableWidgetCoordinates.item(i, 0).text(), AT_LONGITUDE)
            lat = Coordinate(self.dlg.tableWidgetCoordinates.item(i, 1).text(), AT_LATITUDE)
            lon_dd = lon.convert_to_dd()
            lat_dd = lat.convert_to_dd()

            if lon_dd is not None and lat_dd is not None:
                point = QgsPointXY(lon_dd, lat_dd)
                points.append(point)

        return points

    def add_features(self, points: list[QgsPointXY]) -> None:
        """Create and add features to the output layer.

        :param points: Points used to construct the new features (geometries extracted from plain text).
        """
        geometry_type = self.dlg.get_output_geometry_type()
        feature_name = self.dlg.lineEditFeatureName.text().strip()

        features = create_features(
            self.output_layer.fields(),
            geometry_type,
            points,
            feature_name,
        )

        try:
            add_features_to_layer(self.output_layer, features)
        except AddingFeaturesException as e:
            QMessageBox.critical(QWidget(), "Message", str(e))
        else:
            self.iface.mapCanvas().setExtent(self.output_layer.extent())
            self.iface.mapCanvas().refresh()

    def get_or_create_output_layer(self) -> QgsVectorLayer | None:
        """Get an existing output layer or create a new one if matching layer name and geometry type not found in
        Table of Contents."""
        layer_name = self.dlg.lineEditOutputLayerName.text().strip()

        layers = self.get_matching_layers_from_map(layer_name)

        if not layers:
            return create_output_layer(
                layer_name=layer_name,
                geometry_type=self.dlg.get_output_geometry_type(),
            )

        if len(layers) > 1:
            QMessageBox.critical(QWidget(),
                                 "Message",
                                 f"{len(layers)} matching layers with name {self.dlg.lineEditOutputLayerName.text().strip()}")
            return None

        return layers[0]

    def process_coordinates(self, coordinates: list[tuple[str, str]]) -> None:
        """Display coordinates and add corresponding features.

        :param coordinates: extracted coordinates from plain text.
        """
        self.mark_coordinates(coordinates)
        self.fill_in_coordinate_list(coordinates)
        self.add_features(self.get_qgspoints())

    def plain_text_to_geometry(self) -> None:
        """Extract coordinates from plain text"""
        try:
            self.dlg.validate()
        except FormValidationException as e:
            QMessageBox.critical(QWidget(), "Message", str(e))
            return

        self.coordinates_extracted = False
        self.output_layer = self.get_or_create_output_layer()
        if not self.output_layer:
            return

        if not self.output_layer:
            return

        self.iface.setActiveLayer(self.output_layer)

        coordinates = self.get_coordinates_from_plain_text()
        if not coordinates:
            self.dlg.clear_extracted_coordinates()
            self.coordinates_extracted = False

        self.process_coordinates(coordinates)
        self.coordinates_extracted = True

    def run(self) -> None:
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False
            self.dlg = PlainTextToGeometryDialog()
            self.dlg.comboBoxCoordinatesSequence.currentIndexChanged.connect(self.set_coordinate_pair_format)
            self.dlg.comboBoxCoordinatesSeparator.currentIndexChanged.connect(self.set_coordinate_pair_format)
            self.dlg.comboBoxCoordinatesFormat.currentIndexChanged.connect(self.set_coordinate_pair_format)
            self.dlg.pushButtonCancel.clicked.connect(self.dlg.close)
            self.dlg.pushButtoPlainTextToGeometry.clicked.connect(self.plain_text_to_geometry)
            self.dlg.textEditPlainText.textChanged.connect(self.input_data_changes)
            self.dlg.comboBoxOutputGeometryType.currentIndexChanged.connect(self.input_data_changes)
            self.dlg.lineEditOutputLayerName.textChanged.connect(self.input_data_changes)
            self.dlg.lineEditFeatureName.textChanged.connect(self.input_data_changes)

        # show the dialog
        self.dlg.show()
        self.dlg.reset()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
