# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlainTextToGeometryDialog
                                 A QGIS plugin
 Extract coordinates from plain text and create points, line or polygon
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-22
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Paweł Strzelewicz
        email                : @
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import re

import cycler
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

from .aviation_gis_toolkit.coordinate_extraction import (
    COORD_PAIR_SEP_NONE,
    COORD_PAIR_SEP_SPACE,
    COORD_PAIR_SEP_HYPHEN,
    COORD_PAIR_SEP_SLASH,
    COORD_PAIR_SEP_BACKSLASH,
    DMSH_COMP,
    HDMS_COMP,
    DMSH_SEP,
    HDMS_SEP,
    SEQUENCE_LON_LAT,
    SEQUENCE_LAT_LON,
)
from .plugin_types import CoordinatePair
from .exceptions import FormValidationException


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'plaintext_to_geometry_dialog_base.ui'))


class PlainTextToGeometryDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None) -> None:
        """Constructor."""
        super(PlainTextToGeometryDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self._setup_coordinate_format_combos()

    def _setup_coordinate_format_combos(self):
        """Initialize coordinate format combo boxes with supported options."""
        self.comboBoxCoordinatesSequence.clear()
        self.comboBoxCoordinatesSequence.addItem(
            "LAT LON",
            SEQUENCE_LAT_LON,
        )
        self.comboBoxCoordinatesSequence.addItem(
            "LON LAT",
            SEQUENCE_LON_LAT,
        )

        self.comboBoxCoordinatesSeparator.clear()
        self.comboBoxCoordinatesSeparator.addItem(
            "(not separated)",
            COORD_PAIR_SEP_NONE,
        )
        self.comboBoxCoordinatesSeparator.addItem(
            "(Space)",
            COORD_PAIR_SEP_SPACE,
        )
        self.comboBoxCoordinatesSeparator.addItem(
            "-(Hyphen)",
            COORD_PAIR_SEP_HYPHEN,
        )
        self.comboBoxCoordinatesSeparator.addItem(
            "/(Slash)",
            COORD_PAIR_SEP_SLASH,
        )
        self.comboBoxCoordinatesSeparator.addItem(
            "\(Backslash)",
            COORD_PAIR_SEP_BACKSLASH,
        )

        self.comboBoxCoordinatesFormat.clear()
        self.comboBoxCoordinatesFormat.addItem(
            "DMSH compacted",
            DMSH_COMP,
        )
        self.comboBoxCoordinatesFormat.addItem(
            "HDMS compacted",
            HDMS_COMP,
        )
        self.comboBoxCoordinatesFormat.addItem(
            "DMSH separated",
            DMSH_SEP,
        )
        self.comboBoxCoordinatesFormat.addItem(
            "HDMS separated",
            HDMS_SEP,
        )

    def reset(self) -> None:
        """Set plugin widgets to initial state such as:
        - coordinate pair format is not defined
        - coordinate list is empty
        - plain text is empty
        """
        self.comboBoxCoordinatesSequence.setCurrentIndex(-1)
        self.comboBoxCoordinatesSeparator.setCurrentIndex(-1)
        self.comboBoxCoordinatesFormat.setCurrentIndex(-1)
        self.labelCoordinatesExample.setText('Define coordinate format to see example')
        self.lineEditOutputLayerName.clear()
        self.comboBoxOutputGeometryType.setCurrentIndex(0)
        self.lineEditFeatureName.clear()
        self.textEditPlainText.clear()
        self.tableWidgetCoordinates.setRowCount(0)

    def clear_extracted_coordinates(self) -> None:
        """Clear extracted coordinates and their visual representation."""
        self.tableWidgetCoordinates.setRowCount(0)
        html = self.textEditPlainText.toHtml()
        html = html.replace('<span style=" color:#008000;">', '')
        html = html.replace('</span>', '')
        # Prevent setHtml() from triggering text-change signals recursively.
        self.textEditPlainText.blockSignals(True)
        self.textEditPlainText.setHtml(html)
        self.textEditPlainText.blockSignals(False)

    def get_output_geometry_type(self) -> str:
        """Return the selected QGIS output layer geometry type."""
        geometry_type = self.comboBoxOutputGeometryType.currentText()
        if geometry_type == 'Line':
            geometry_type += 'String'
        return geometry_type

    def add_coordinate_row(self, coordinate: CoordinatePair) -> None:
        """Add a coordinate pair as a new row in the extracted coordinate table.

        :param coordinate: Coordinate pair
        """
        row_pos = self.tableWidgetCoordinates.rowCount()
        self.tableWidgetCoordinates.insertRow(row_pos)
        self.tableWidgetCoordinates.setItem(row_pos, 0, QtWidgets.QTableWidgetItem(coordinate.longitude))
        self.tableWidgetCoordinates.setItem(row_pos, 1, QtWidgets.QTableWidgetItem(coordinate.latitude))

    def populate_coordinate_table(self, coordinate_list: list[CoordinatePair]) -> None:
        """Populate the coordinate table with a list of extracted coordinate pairs.

        :param coordinate_list: Normalised coordinate pairs (order lon, lat) to add to the table.
        """
        self.tableWidgetCoordinates.setRowCount(0)
        for c in coordinate_list:
            self.add_coordinate_row(c)

    def mark_coordinates(self,
                         coordinates: list[CoordinatePair],
                         coord_order: str,
                         coord_sep: str) -> None:
        """Mark extracted coordinates in the plain text widget in green.

        :param coordinates: Extracted coordinate pair
        :param coord_order: Coordinate order
        :param coord_sep: Separator used between coordinate values
        """
        text = self.textEditPlainText.toHtml()

        if coord_order == SEQUENCE_LON_LAT:
            coordinates = ((c.longitude, c.latitude) for c in coordinates)
        else:
            coordinates = ((c.latitude, c.longitude) for c in coordinates)

        for first, second in coordinates:
            coord_pair = f"{first}{coord_sep}{second}"
            marked_pair = f'<span style="color:green;">{coord_pair}</span>'
            text = re.sub(re.escape(coord_pair), marked_pair, text)

        self.textEditPlainText.setHtml(text)

    def is_coordinate_format_set(self) -> bool:
        """Check whether all coordinate format options have been selected.

          Returns:
              bool: True if coordinate sequence, separator, and format are set;
                  otherwise, False.
          """
        return all(
            combo.currentData() is not None
            for combo in (
                self.comboBoxCoordinatesSequence,
                self.comboBoxCoordinatesSeparator,
                self.comboBoxCoordinatesFormat,
            )
        )

    def validate(self) -> None:
        """Validate that all required form fields are set.

        Raises:
            FormValidationException: If one or more required fields are not set.
                The exception message lists all missing fields.
        """
        missing = []
        line_edit_fields = (
            (self.lineEditOutputLayerName, "Output layer is required."),
            (self.lineEditFeatureName, "Feature name is required.")
        )

        if not self.textEditPlainText.toPlainText():
            missing.append("Plain text is required.")

        for field, name in line_edit_fields:
            if not field.text().strip():
                missing.append(name)

        if not self.is_coordinate_format_set():
            missing.append("Coordinate format is required.")

        if missing:
            raise FormValidationException(
                "The following fields are required:\n\n"
                + "\n".join(f"• {name}" for name in missing)
            )
