# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlainTextToGeometryDialog
                                 A QGIS plugin
 Extract coordinates from plain text and create points, line or polygon
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-22
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Paweł Strzelewicz
        email                : @
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

from ._exceptions import FormValidationException


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'plaintext_to_geometry_dialog_base.ui'))


class PlainTextToGeometryDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(PlainTextToGeometryDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

    def is_coordinate_format_set(self) -> bool:
        """Check whether all coordinate format options have been selected.

          Returns:
              bool: True if coordinate sequence, separator, and format are set;
                  otherwise, False.
          """
        return (
            self.comboBoxCoordinatesSequence.currentIndex() >= 1
            and self.comboBoxCoordinatesSeparator.currentIndex() >= 1
            and self.comboBoxCoordinatesFormat.currentIndex() >= 1
        )

    def validate(self) -> None:
        """Validate that all required form fields are set.

        Raises:
            FormValidationException: If one or more required fields are not set.
                The exception message lists all missing fields.
        """
        missing = []
        line_edit_fields = (
            (self.lineEditOutputLayerName, "Output layer is required."),
            (self.lineEditFeatureName, "Feature name is required.")
        )

        if not self.textEditPlainText.toPlainText():
            missing.append("Plain text is required.")

        for field, name in line_edit_fields:
            if not field.text().strip():
                missing.append(name)

        if not self.is_coordinate_format_set():
            missing.append("Coordinate format is required.")

        if missing:
            raise FormValidationException(
                "The following fields are required:\n\n"
                + "\n".join(f"• {name}" for name in missing)
            )
